// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/omaigo88/inventory/pkg/repository"
	"github.com/omaigo88/shared/pkg/proto/inventory/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type MockService
func (_mock *MockService) GetPart(ctx context.Context, rawUUID string) (repository.Part, error) {
	ret := _mock.Called(ctx, rawUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 repository.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.Part, error)); ok {
		return returnFunc(ctx, rawUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.Part); ok {
		r0 = returnFunc(ctx, rawUUID)
	} else {
		r0 = ret.Get(0).(repository.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type MockService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - rawUUID string
func (_e *MockService_Expecter) GetPart(ctx interface{}, rawUUID interface{}) *MockService_GetPart_Call {
	return &MockService_GetPart_Call{Call: _e.mock.On("GetPart", ctx, rawUUID)}
}

func (_c *MockService_GetPart_Call) Run(run func(ctx context.Context, rawUUID string)) *MockService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetPart_Call) Return(part repository.Part, err error) *MockService_GetPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockService_GetPart_Call) RunAndReturn(run func(ctx context.Context, rawUUID string) (repository.Part, error)) *MockService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type MockService
func (_mock *MockService) ListParts(ctx context.Context, partType inventoryv1.PartType, rawUUIDs []string) ([]repository.Part, error) {
	ret := _mock.Called(ctx, partType, rawUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []repository.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inventoryv1.PartType, []string) ([]repository.Part, error)); ok {
		return returnFunc(ctx, partType, rawUUIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inventoryv1.PartType, []string) []repository.Part); ok {
		r0 = returnFunc(ctx, partType, rawUUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inventoryv1.PartType, []string) error); ok {
		r1 = returnFunc(ctx, partType, rawUUIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - partType inventoryv1.PartType
//   - rawUUIDs []string
func (_e *MockService_Expecter) ListParts(ctx interface{}, partType interface{}, rawUUIDs interface{}) *MockService_ListParts_Call {
	return &MockService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, partType, rawUUIDs)}
}

func (_c *MockService_ListParts_Call) Run(run func(ctx context.Context, partType inventoryv1.PartType, rawUUIDs []string)) *MockService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inventoryv1.PartType
		if args[1] != nil {
			arg1 = args[1].(inventoryv1.PartType)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListParts_Call) Return(parts []repository.Part, err error) *MockService_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockService_ListParts_Call) RunAndReturn(run func(ctx context.Context, partType inventoryv1.PartType, rawUUIDs []string) ([]repository.Part, error)) *MockService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
