// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/omaigo88/shared/pkg/proto/payment/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockService
func (_mock *MockService) PayOrder(ctx context.Context, orderUUID string, method paymentv1.PaymentMethod) (string, error) {
	ret := _mock.Called(ctx, orderUUID, method)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, paymentv1.PaymentMethod) (string, error)); ok {
		return returnFunc(ctx, orderUUID, method)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, paymentv1.PaymentMethod) string); ok {
		r0 = returnFunc(ctx, orderUUID, method)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, paymentv1.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, orderUUID, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - method paymentv1.PaymentMethod
func (_e *MockService_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, method interface{}) *MockService_PayOrder_Call {
	return &MockService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, method)}
}

func (_c *MockService_PayOrder_Call) Run(run func(ctx context.Context, orderUUID string, method paymentv1.PaymentMethod)) *MockService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 paymentv1.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(paymentv1.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_PayOrder_Call) Return(s string, err error) *MockService_PayOrder_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID string, method paymentv1.PaymentMethod) (string, error)) *MockService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
