// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/omaigo88/shared/pkg/proto/payment/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockPaymentClient creates a new instance of MockPaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentClient {
	mock := &MockPaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentClient is an autogenerated mock type for the PaymentClient type
type MockPaymentClient struct {
	mock.Mock
}

type MockPaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentClient) EXPECT() *MockPaymentClient_Expecter {
	return &MockPaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockPaymentClient
func (_mock *MockPaymentClient) PayOrder(ctx context.Context, in *paymentv1.PayOrderRequest, opts ...grpc.CallOption) (*paymentv1.PayOrderResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *paymentv1.PayOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *paymentv1.PayOrderRequest, ...grpc.CallOption) (*paymentv1.PayOrderResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *paymentv1.PayOrderRequest, ...grpc.CallOption) *paymentv1.PayOrderResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentv1.PayOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *paymentv1.PayOrderRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *paymentv1.PayOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockPaymentClient_Expecter) PayOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockPaymentClient_PayOrder_Call {
	return &MockPaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockPaymentClient_PayOrder_Call) Run(run func(ctx context.Context, in *paymentv1.PayOrderRequest, opts ...grpc.CallOption)) *MockPaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *paymentv1.PayOrderRequest
		if args[1] != nil {
			arg1 = args[1].(*paymentv1.PayOrderRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPaymentClient_PayOrder_Call) Return(payOrderResponse *paymentv1.PayOrderResponse, err error) *MockPaymentClient_PayOrder_Call {
	_c.Call.Return(payOrderResponse, err)
	return _c
}

func (_c *MockPaymentClient_PayOrder_Call) RunAndReturn(run func(ctx context.Context, in *paymentv1.PayOrderRequest, opts ...grpc.CallOption) (*paymentv1.PayOrderResponse, error)) *MockPaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
