// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTrManager creates a new instance of MockTrManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrManager {
	mock := &MockTrManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrManager is an autogenerated mock type for the TrManager type
type MockTrManager struct {
	mock.Mock
}

type MockTrManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrManager) EXPECT() *MockTrManager_Expecter {
	return &MockTrManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockTrManager
func (_mock *MockTrManager) Do(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockTrManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTrManager_Expecter) Do(ctx interface{}, fn interface{}) *MockTrManager_Do_Call {
	return &MockTrManager_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *MockTrManager_Do_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTrManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrManager_Do_Call) Return(err error) *MockTrManager_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrManager_Do_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTrManager_Do_Call {
	_c.Call.Return(run)
	return _c
}
