// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	"github.com/omaigo88/order/pkg/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(id uuid.UUID) (repository.Order, bool) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 repository.Order
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (repository.Order, bool)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) repository.Order); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(repository.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) bool); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Get(id interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockRepository_Get_Call) Run(run func(id uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(order repository.Order, b bool) *MockRepository_Get_Call {
	_c.Call.Return(order, b)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(id uuid.UUID) (repository.Order, bool)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(order repository.Order) {
	_mock.Called(order)
	return
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - order repository.Order
func (_e *MockRepository_Expecter) Save(order interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", order)}
}

func (_c *MockRepository_Save_Call) Run(run func(order repository.Order)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repository.Order
		if args[0] != nil {
			arg0 = args[0].(repository.Order)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return() *MockRepository_Save_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(order repository.Order)) *MockRepository_Save_Call {
	_c.Run(run)
	return _c
}
