// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	"github.com/omaigo88/inventory/pkg/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPart(id uuid.UUID) (repository.Part, bool) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 repository.Part
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (repository.Part, bool)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) repository.Part); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(repository.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) bool); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type MockRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetPart(id interface{}) *MockRepository_GetPart_Call {
	return &MockRepository_GetPart_Call{Call: _e.mock.On("GetPart", id)}
}

func (_c *MockRepository_GetPart_Call) Run(run func(id uuid.UUID)) *MockRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetPart_Call) Return(part repository.Part, b bool) *MockRepository_GetPart_Call {
	_c.Call.Return(part, b)
	return _c
}

func (_c *MockRepository_GetPart_Call) RunAndReturn(run func(id uuid.UUID) (repository.Part, bool)) *MockRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type MockRepository
func (_mock *MockRepository) ListParts() []repository.Part {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []repository.Part
	if returnFunc, ok := ret.Get(0).(func() []repository.Part); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Part)
		}
	}
	return r0
}

// MockRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
func (_e *MockRepository_Expecter) ListParts() *MockRepository_ListParts_Call {
	return &MockRepository_ListParts_Call{Call: _e.mock.On("ListParts")}
}

func (_c *MockRepository_ListParts_Call) Run(run func()) *MockRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_ListParts_Call) Return(parts []repository.Part) *MockRepository_ListParts_Call {
	_c.Call.Return(parts)
	return _c
}

func (_c *MockRepository_ListParts_Call) RunAndReturn(run func() []repository.Part) *MockRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
