// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/omaigo88/inventory/pkg/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPart(ctx context.Context, id uuid.UUID) (repository.Part, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 repository.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.Part, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.Part); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type MockRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetPart(ctx interface{}, id interface{}) *MockRepository_GetPart_Call {
	return &MockRepository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, id)}
}

func (_c *MockRepository_GetPart_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetPart_Call) Return(part repository.Part, err error) *MockRepository_GetPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockRepository_GetPart_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repository.Part, error)) *MockRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type MockRepository
func (_mock *MockRepository) ListParts(ctx context.Context) ([]repository.Part, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []repository.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repository.Part, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repository.Part); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListParts(ctx interface{}) *MockRepository_ListParts_Call {
	return &MockRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx)}
}

func (_c *MockRepository_ListParts_Call) Run(run func(ctx context.Context)) *MockRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListParts_Call) Return(parts []repository.Part, err error) *MockRepository_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockRepository_ListParts_Call) RunAndReturn(run func(ctx context.Context) ([]repository.Part, error)) *MockRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
