// Package api implements the OrderService HTTP transport layer.
package api

import (
	"context"
	"errors"
	"net/http"

	"github.com/google/uuid"

	"github.com/omaigo88/order/pkg/repository"
	orderService "github.com/omaigo88/order/pkg/service"
	orderv1 "github.com/omaigo88/shared/pkg/openapi/order/v1"
)

// Service is the business-logic dependency required by Handler.
type Service interface {
	CreateOrder(ctx context.Context, input orderService.CreateOrderInput) (repository.Order, error)
	GetOrder(ctx context.Context, id uuid.UUID) (repository.Order, error)
	PayOrder(ctx context.Context, id uuid.UUID, method repository.PaymentMethod) (repository.Order, error)
	CancelOrder(ctx context.Context, id uuid.UUID) (repository.Order, error)
}

// Handler implements the orderv1.Handler interface generated by ogen.
type Handler struct {
	orderv1.UnimplementedHandler
	svc Service
}

// NewHandler creates a new order handler.
func NewHandler(svc Service) *Handler {
	return &Handler{svc: svc}
}

// SetupServer creates an OpenAPI server based on the handler.
func SetupServer(h *Handler) (*orderv1.Server, error) {
	return orderv1.NewServer(h)
}

// toOrderDto converts a repository.Order to orderv1.OrderDto.
func toOrderDto(order repository.Order) *orderv1.OrderDto {
	var shieldUUID orderv1.OptNilUUID
	if order.ShieldUUID != nil {
		shieldUUID = orderv1.NewOptNilUUID(*order.ShieldUUID)
	}

	var weaponUUID orderv1.OptNilUUID
	if order.WeaponUUID != nil {
		weaponUUID = orderv1.NewOptNilUUID(*order.WeaponUUID)
	}

	var transactionUUID orderv1.OptNilUUID
	if order.TransactionUUID != nil {
		transactionUUID = orderv1.NewOptNilUUID(*order.TransactionUUID)
	}

	var paymentMethod orderv1.OptNilPaymentMethod
	if order.PaymentMethod != nil {
		paymentMethod = orderv1.NewOptNilPaymentMethod(orderv1.PaymentMethod(*order.PaymentMethod))
	}

	return &orderv1.OrderDto{
		OrderUUID:       order.OrderUUID,
		HullUUID:        order.HullUUID,
		EngineUUID:      order.EngineUUID,
		ShieldUUID:      shieldUUID,
		WeaponUUID:      weaponUUID,
		TotalPrice:      order.TotalPrice,
		TransactionUUID: transactionUUID,
		PaymentMethod:   paymentMethod,
		Status:          orderv1.OrderStatus(order.Status),
		CreatedAt:       order.CreatedAt,
	}
}

// GetOrder implements the getOrder operation
// GET /api/v1/orders/{order_uuid}.
func (h *Handler) GetOrder(ctx context.Context, params orderv1.GetOrderParams) (orderv1.GetOrderRes, error) {
	order, err := h.svc.GetOrder(ctx, params.OrderUUID)
	if err != nil {
		if errors.Is(err, orderService.ErrOrderNotFound) {
			return &orderv1.GetOrderNotFound{
				Code:    http.StatusNotFound,
				Message: "order not found",
			}, nil
		}

		return nil, err
	}

	return toOrderDto(order), nil
}

// CreateOrder implements the createOrder operation
// POST /api/v1/orders.
func (h *Handler) CreateOrder(ctx context.Context, req *orderv1.CreateOrderRequest) (orderv1.CreateOrderRes, error) {
	input := orderService.CreateOrderInput{
		HullUUID:   req.GetHullUUID(),
		EngineUUID: req.GetEngineUUID(),
	}

	if shieldUUID, ok := req.GetShieldUUID().Get(); ok {
		input.ShieldUUID = &shieldUUID
	}

	if weaponUUID, ok := req.GetWeaponUUID().Get(); ok {
		input.WeaponUUID = &weaponUUID
	}

	order, err := h.svc.CreateOrder(ctx, input)
	if err != nil {
		switch {
		case errors.Is(err, orderService.ErrComponentNotFound):
			return &orderv1.CreateOrderNotFound{
				Code:    http.StatusNotFound,
				Message: err.Error(),
			}, nil
		case errors.Is(err, orderService.ErrComponentOutOfStock):
			return &orderv1.CreateOrderConflict{
				Code:    http.StatusConflict,
				Message: err.Error(),
			}, nil
		default:
			return nil, err
		}
	}

	return &orderv1.CreateOrderResponse{
		OrderUUID:  order.OrderUUID,
		TotalPrice: order.TotalPrice,
	}, nil
}

// PayOrder implements the payOrder operation
// POST /api/v1/orders/{order_uuid}/pay.
func (h *Handler) PayOrder(ctx context.Context, req *orderv1.PayOrderRequest, params orderv1.PayOrderParams) (orderv1.PayOrderRes, error) {
	method := repository.PaymentMethod(req.GetPaymentMethod())

	order, err := h.svc.PayOrder(ctx, params.OrderUUID, method)
	if err != nil {
		switch {
		case errors.Is(err, orderService.ErrOrderNotFound):
			return &orderv1.PayOrderNotFound{
				Code:    http.StatusNotFound,
				Message: "order not found",
			}, nil
		case errors.Is(err, orderService.ErrOrderAlreadyFinal):
			return &orderv1.PayOrderConflict{
				Code:    http.StatusConflict,
				Message: "order is already paid or cancelled",
			}, nil
		default:
			return nil, err
		}
	}

	return &orderv1.PayOrderResponse{
		TransactionUUID: *order.TransactionUUID,
	}, nil
}

// CancelOrder implements the cancelOrder operation
// POST /api/v1/orders/{order_uuid}/cancel.
func (h *Handler) CancelOrder(ctx context.Context, params orderv1.CancelOrderParams) (orderv1.CancelOrderRes, error) {
	_, err := h.svc.CancelOrder(ctx, params.OrderUUID)
	if err != nil {
		switch {
		case errors.Is(err, orderService.ErrOrderNotFound):
			return &orderv1.CancelOrderNotFound{
				Code:    http.StatusNotFound,
				Message: "order not found",
			}, nil
		case errors.Is(err, orderService.ErrOrderAlreadyFinal):
			return &orderv1.CancelOrderConflict{
				Code:    http.StatusConflict,
				Message: "order is already paid or cancelled",
			}, nil
		default:
			return nil, err
		}
	}

	return &orderv1.CancelOrderResponse{}, nil
}
