// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/omaigo88/order/pkg/repository"
	"github.com/omaigo88/order/pkg/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type MockService
func (_mock *MockService) CancelOrder(ctx context.Context, id uuid.UUID) (repository.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 repository.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) CancelOrder(ctx interface{}, id interface{}) *MockService_CancelOrder_Call {
	return &MockService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, id)}
}

func (_c *MockService_CancelOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CancelOrder_Call) Return(order repository.Order, err error) *MockService_CancelOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repository.Order, error)) *MockService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockService
func (_mock *MockService) CreateOrder(ctx context.Context, input service.CreateOrderInput) (repository.Order, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 repository.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.CreateOrderInput) (repository.Order, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.CreateOrderInput) repository.Order); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(repository.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, service.CreateOrderInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - input service.CreateOrderInput
func (_e *MockService_Expecter) CreateOrder(ctx interface{}, input interface{}) *MockService_CreateOrder_Call {
	return &MockService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, input)}
}

func (_c *MockService_CreateOrder_Call) Run(run func(ctx context.Context, input service.CreateOrderInput)) *MockService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 service.CreateOrderInput
		if args[1] != nil {
			arg1 = args[1].(service.CreateOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateOrder_Call) Return(order repository.Order, err error) *MockService_CreateOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, input service.CreateOrderInput) (repository.Order, error)) *MockService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockService
func (_mock *MockService) GetOrder(ctx context.Context, id uuid.UUID) (repository.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 repository.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) GetOrder(ctx interface{}, id interface{}) *MockService_GetOrder_Call {
	return &MockService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockService_GetOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetOrder_Call) Return(order repository.Order, err error) *MockService_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repository.Order, error)) *MockService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type MockService
func (_mock *MockService) PayOrder(ctx context.Context, id uuid.UUID, method repository.PaymentMethod) (repository.Order, error) {
	ret := _mock.Called(ctx, id, method)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 repository.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, repository.PaymentMethod) (repository.Order, error)); ok {
		return returnFunc(ctx, id, method)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, repository.PaymentMethod) repository.Order); ok {
		r0 = returnFunc(ctx, id, method)
	} else {
		r0 = ret.Get(0).(repository.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, repository.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, id, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - method repository.PaymentMethod
func (_e *MockService_Expecter) PayOrder(ctx interface{}, id interface{}, method interface{}) *MockService_PayOrder_Call {
	return &MockService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, id, method)}
}

func (_c *MockService_PayOrder_Call) Run(run func(ctx context.Context, id uuid.UUID, method repository.PaymentMethod)) *MockService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 repository.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(repository.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_PayOrder_Call) Return(order repository.Order, err error) *MockService_PayOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, method repository.PaymentMethod) (repository.Order, error)) *MockService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
